# Generated by Django 4.2.5 on 2023-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images/'),
        ),
    ]
