# Generated by Django 4.2.5 on 2024-01-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('power', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='pvpowerplant',
            name='solar_panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_pv_designer.solarpanel'),
        ),
    ]
