# Generated by Django 4.2.5 on 2024-01-05 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpowerplant',
            name='user',
        ),
        migrations.AddField(
            model_name='mapdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
