# Generated by Django 4.2.5 on 2024-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpowerplant',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvpowerplant',
            name='consumption_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvpowerplant',
            name='consumption_per_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvpowerplant',
            name='discharge_cutoff_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvpowerplant',
            name='off_grid',
            field=models.BooleanField(default=False),
        ),
    ]
