# Generated by Django 4.2.5 on 2024-03-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvpowerplant',
            old_name='pv_power_plant',
            new_name='system_details',
        ),
    ]
