# Generated by Django 4.2.5 on 2024-02-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdata',
            name='areasData',
        ),
    ]
