# Generated by Django 4.2.5 on 2024-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_solarpanel_pvpowerplant_solar_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarpanel',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
