# Generated by Django 4.2.4 on 2023-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_alter_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPVCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_peak_power', models.FloatField()),
                ('system_loss', models.FloatField()),
                ('mounting_position', models.CharField(choices=[('option1', 'Free standing'), ('option2', 'Roof added')], max_length=20)),
                ('slope', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('optimize_slope', models.BooleanField(default=False)),
                ('optimize_slope_and_azimuth', models.BooleanField(default=False)),
                ('pv_electricity_price', models.BooleanField(default=False)),
                ('pv_system_cost', models.FloatField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
