# Generated by Django 4.2.5 on 2024-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_pvpowerplant_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpowerplant',
            name='known_consumption',
            field=models.BooleanField(default=False),
        ),
    ]
