# Generated by Django 4.2.5 on 2024-02-25 10:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_remove_mapdata_areasdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
