# Generated by Django 4.2.5 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_remove_pvpowerplant_user_mapdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpowerplant',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
