# Generated by Django 4.2.5 on 2024-03-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0002_rename_pv_power_plant_pvpowerplant_system_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvsystemdetails',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='pvsystemdetails',
            name='consumption_per_day',
        ),
        migrations.RemoveField(
            model_name='pvsystemdetails',
            name='discharge_cutoff_limit',
        ),
        migrations.RemoveField(
            model_name='pvsystemdetails',
            name='off_grid',
        ),
    ]
