# Generated by Django 4.2.5 on 2024-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_pvpowerplant_known_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpanel',
            name='pv_technology',
            field=models.CharField(choices=[('crystSi', 'Crystalline silicon'), ('CIS', 'Copper indium selenide'), ('CdTe', 'Cadmium telluride'), ('Unknown', 'Unknown')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
