# Generated by Django 4.2.5 on 2024-02-25 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_customuser_home_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
