# Generated by Django 4.2.5 on 2024-01-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_pvpowerplant_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpowerplant',
            name='solar_panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web_pv_designer.solarpanel'),
        ),
        migrations.DeleteModel(
            name='SolarPVCalculator',
        ),
    ]
