# Generated by Django 4.2.5 on 2024-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_remove_solarpanel_dimensions_solarpanel_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='installed_peak_power',
        ),
    ]
