# Generated by Django 4.2.5 on 2024-03-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_remove_pvsystemdetails_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvsystemdetails',
            name='known_consumption',
        ),
    ]
