# Generated by Django 4.2.4 on 2023-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0003_solarpvcalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpvcalculator',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarpvcalculator',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
