# Generated by Django 4.2.4 on 2023-08-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0004_solarpvcalculator_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpvcalculator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
