# Generated by Django 4.2.5 on 2024-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0004_remove_area_installed_peak_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpowerplant',
            name='panel_power',
        ),
        migrations.AddField(
            model_name='area',
            name='installed_peak_power',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
