# Generated by Django 4.2.5 on 2024-02-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0004_area_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdata',
            name='areas',
        ),
    ]
