# Generated by Django 4.2.5 on 2024-02-04 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0004_solarpanel_pv_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpanel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
