# Generated by Django 4.2.5 on 2024-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0004_alter_pvpowerplant_solar_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='rotations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
