# Generated by Django 4.2.5 on 2024-03-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0005_remove_mapdata_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('consumption', models.FloatField()),
                ('power_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_consumptions', to='web_pv_designer.pvpowerplant')),
            ],
            options={
                'unique_together': {('power_plant', 'month')},
            },
        ),
    ]
