# Generated by Django 4.2.4 on 2023-08-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0005_solarpvcalculator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarpvcalculator',
            name='user',
        ),
    ]
