# Generated by Django 4.2.5 on 2024-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0005_solarpanel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='mounting_position',
            field=models.CharField(choices=[('option1', 'Free standing'), ('option2', 'Roof added'), ('option3', 'Optimize position')], max_length=20),
        ),
    ]
