# Generated by Django 4.2.5 on 2024-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0006_alter_area_mounting_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='mounting_position',
            field=models.CharField(choices=[('free', 'Free standing'), ('building', 'Roof added'), ('optimize', 'Optimize position')], max_length=20),
        ),
    ]
