# Generated by Django 4.2.5 on 2024-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pv_designer', '0007_alter_area_mounting_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpanel',
            name='manufacturer',
            field=models.CharField(default='brand', max_length=100),
            preserve_default=False,
        ),
    ]
